# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=2)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('config', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeightSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('options', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='weightconfig',
            name='weight_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WeightSet'),
        ),
    ]
