# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161229_1130'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='exercise',
        ),
        migrations.AlterModelTable(
            name='programme',
            table='programme',
        ),
        migrations.AlterModelTable(
            name='weightconfig',
            table='weightconfig',
        ),
        migrations.AlterModelTable(
            name='weightset',
            table='weightset',
        ),
        migrations.AlterModelTable(
            name='workout',
            table='workout',
        ),
    ]
