# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161229_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='last_workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Programme'),
            preserve_default=False,
        ),
    ]
